# Generated by Django 4.0.1 on 2022-01-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=255)),
                ('Bp', models.CharField(max_length=255)),
                ('Sg', models.CharField(max_length=255)),
                ('Al', models.CharField(max_length=255)),
                ('Su', models.CharField(max_length=255)),
                ('Rbc', models.CharField(max_length=255)),
                ('Pc', models.CharField(max_length=255)),
                ('Pcc', models.CharField(max_length=255)),
                ('Ba', models.CharField(max_length=255)),
                ('Bgr', models.CharField(max_length=255)),
                ('Bu', models.CharField(max_length=255)),
                ('Sc', models.CharField(max_length=255)),
                ('Sod', models.CharField(max_length=255)),
                ('Pot', models.CharField(max_length=255)),
                ('Hemo', models.CharField(max_length=255)),
                ('Pcv', models.CharField(max_length=255)),
                ('Wc', models.CharField(max_length=255)),
                ('Rc', models.CharField(max_length=255)),
                ('Htn', models.CharField(max_length=255)),
                ('Dm', models.CharField(max_length=255)),
                ('Cad', models.CharField(max_length=255)),
                ('Appet', models.CharField(max_length=255)),
                ('Pe', models.CharField(max_length=255)),
                ('Ane', models.CharField(max_length=255)),
                ('Class', models.CharField(max_length=255)),
            ],
        ),
    ]
