# Generated by Django 4.0.1 on 2022-01-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0003_detail_rule_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_rule',
            name='id_rule',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rule',
            name='id_rule',
            field=models.IntegerField(),
        ),
    ]
