# Generated by Django 4.0.1 on 2022-01-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0004_alter_detail_rule_id_rule_alter_rule_id_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_rule',
            old_name='kelas',
            new_name='atribut',
        ),
        migrations.RenameField(
            model_name='detail_rule',
            old_name='rule',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='atribut',
            new_name='kelas',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='value',
            new_name='rule',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='id_rule',
        ),
    ]
