# Generated by Django 4.0.1 on 2022-01-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0005_rename_kelas_detail_rule_atribut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='diskrit',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
