# Generated by Django 4.0.1 on 2022-02-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0007_kfcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfcv',
            name='kelas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
