# Generated by Django 4.0.1 on 2022-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0008_kfcv_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribut', models.CharField(max_length=255)),
                ('sc', models.CharField(max_length=255)),
            ],
        ),
    ]
