# Generated by Django 4.0.1 on 2022-02-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0010_range_pengujian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kfcv',
            old_name='kelas',
            new_name='jenis',
        ),
    ]
